## callback

- 다른 함수가 실행을 끝낸 뒤 실행되는 callback되는 함수
- 함수를 만들때, parameter 를 함수로 받아서 쓸 수 있는데 그 함수

---

## 비동기 작업과 Promise

- 비동기 작업
  - **특정 코드의 로직이 끝날 때까지 기다림 X, 나머지 코드를 먼저 실행**
  - **빠른 페이지 로딩**을 위해 웹사이트 개발에 비동기 작업이 사용
- 어떻게 순서대로 동기적이게 할까?
  - 콜백 함수
    - 사용은 가능
    - 콜백을 계속 호출하면 코드가 복잡해지고 에러 처리하기 어려움
    - **이런 콜백의 단점을 보완 => Promise**

---

## Promise

- **비동기 함수의 결과를 담고 있는 객체**
- 상태
  - 대기(Pending): 비동기 함수가 아직 시작하지 않은 상태
  - 성공(Fulfilled): 비동기 함수가 성공적으로 완료된 상태
  - 실패(Rejected): 비동기 함수가 실패한 상태
- Promsie가 대기 상태에서 상태가 변화면?
  - then(), catch() 함수를 사용 -> 성공 상태의 Promise, 실패 상태의 Promise를 각각 처리 가능
- 예문
  ```
    paymentWidget.requestPayment({
      orderId: "t9JI0Bs1SVdJxRs8yjiQJ",
      orderName: "토스 티셔츠 외 2건",
    })
    .then(function (data) {
      console.log(data);
      // 성공 처리
    })
    .catch(function (error) {
      // 에러 처리
      if (error.code == "NEED_CARD_PAYMENT_DETAIL") {
        console.log(error.message);
      }
    })
  ```

---

## Promise에도 콜백과 비슷한 문제가 일어날 수 있다?

- then() 체인을 길게 이어 나가면 콜백 체인과 마찬가지로 **코드의 가독성이 떨어지고** **에러가 어디서 일어났는지 보기 어려움**

![alt text](imgs/under_arrow.png)

#### 콜백, Promise 체인의 단점은 async와 await로 보완할 수 있다

- 예문
  - 결제를 요청하고 결제 요청의 결과를 처리하는 handleSubmit() 함수를 정의
  - 함수를 정의할 때 **async**를 함수 앞에 붙임
    => **“이 함수는 비동기적인 함수이고 Promise를 반환한다”라고 선언**하는 것
    - 반환 값이 Promise 생성 함수가 아니어도 반환되는 값을 Promise 객체에 넣는 것
  ```
  async function handleSubmit() {
  	...
  	return paymentData
  	// return Promise.resolve(paymentData) // 위와 같은 결과
  }
  ```

---

## await

- async 함수 안에만 사용할 수 있는 특별한 문법
- **Promise를 반환하는 함수 앞에 await를 붙이면, 해당 Promise의 상태가 바뀔 때까지 코드가 기다려짐**
- Promise가 성공 상태 또는 실패 상태로 바뀌기 전까지는 다음 연산을 시작 X
- await는 then()과 같은 역할을 하는데, 더 편리
  - 콜백 함수를 등록할 필요 X
  - 체이닝으로 인해 코드가 복잡 X
- 예문

  - 결제를 요청하는 requestPayment() 메서드 앞에 await이 있음
  - 결제 요청이 잘 완료되어 paymentData(Promise 객체)의 상태가 바뀐 이후에만 console.log(paymentData)가 실행됨
    => 비동기 작업을 동기적으로 바꾸는 것

  ```

  async function handleSubmit() {
  const paymentData = await paymentWidget.requestPayment({
  orderId: "KOISABLdLiIzeM-VGU_8Z", // 주문 ID(직접 만들어주세요)
  orderName: "토스 티셔츠 외 2건" // 주문명
  });
  console.log(paymentData);
  return paymentData
  }
  ```

---

## 에러 처리?

- **try/catch**
- 예문

  - requestPayment()에서 실패 상태의 Promise를 반환하면, 바로 catch 블록을 실행

  ```
  async function handleSubmit() {
      try {
        const paymentData = await paymentWidget.requestPayment({
          orderId: "KOISABLdLiIzeM-VGU_8Z", // 주문 ID(직접 만들어주세요)
          orderName: "토스 티셔츠 외 2건" // 주문명
        });
      console.log(paymentData);
        // 성공 처리
        return paymentData;
      } catch (error) {
        // 에러 처리
        console.log(error.message);
      }
    }
  ```
